- sl1543:
    interface: esaote # Name of the adapter interface used in the given device.
    aperture:
        - card: 0
          master: True
          origin: 0
          size: 128
        - card: 1
          origin: 0
          size: 64
